Modify acl hook behavior
Devatoria/go-mesos-executor pull request #22
Opened 2017-10-31 14:26 UTC by WinterNis

2017-10-31 14:45 UTC, janisz commented on hook/acl_test.go
> +			[]string{
Do you need to wrap this in slice if you use `...`?

2017-10-31 14:45 UTC, janisz commented on hook/acl.go
> +			var port mesos.ContainerInfo_DockerInfo_PortMapping
`port` → `portMapping` the you read GetHostPort from port, it looks weird.

2017-10-31 15:06 UTC, tgermain requested changes

2017-10-31 15:06 UTC, tgermain commented on hook/acl.go
> +			portIndex, err = strconv.Atoi(match[1])
check `match` len before accessing it.

2017-11-02 15:01 UTC, Devatoria commented on hook/acl.go
> +var aclHookLabel = regexp.MustCompile("ACL_(?P<portIndex>[0-9]+)_ALLOWED")
EXECUTOR_<port>_ACL

2017-11-02 15:07 UTC, Devatoria requested changes

2017-11-02 15:07 UTC, Devatoria commented on hook/acl.go
> +func checkChain(driver *iptables.IPTables) (string, error) {
Please comment this function

2017-11-02 15:07 UTC, Devatoria commented on hook/acl.go
> +	}
Please jump line

2017-11-02 15:07 UTC, Devatoria commented on hook/acl.go
> +func generateACL(
Please comment function

2017-11-02 15:07 UTC, Devatoria commented on hook/acl.go
> +	for _, label := range info.GetLabels().GetLabels() {
Please comment this (very long) loop

2017-11-02 15:07 UTC, Devatoria commented on hook/acl.go
> +	}
Please jump line

2017-11-02 15:07 UTC, Devatoria commented on hook/acl_test.go
> +
Empty line

2017-11-02 15:07 UTC, Devatoria commented on hook/acl_test.go
> +		rules)
Jump a line between rules and )

2017-11-02 15:07 UTC, Devatoria commented on hook/acl_test.go
> +
Empty line

2017-11-02 15:07 UTC, Devatoria commented on hook/acl_test.go
> +		rules)
LJ between rules and )

2017-11-02 15:07 UTC, Devatoria commented on hook/acl_test.go
> +
Empty line

2017-11-02 15:07 UTC, Devatoria commented on hook/acl_test.go
> +
Empty line

2017-11-02 15:48 UTC, Devatoria approved these changes

2017-11-02 15:48 UTC, merged